---
- name: Install the Elastic.co PGP Key for YUM
  rpm_key:
    key: "{{ kibana_repo_key }}"
    state: present

- name: Add Elastic.co YUM Repo
  yum_repository:
    name: "elasticsearch-{{ es_major_version }}"
    baseurl: "https://artifacts.elastic.co/packages/{{ es_major_version }}/yum"
    description: "Elasticsearch repository for {{ es_major_version }} packages"
    gpgcheck: 1
    gpgkey: "{{ kibana_repo_key }}"
    enabled: 1
